### ISSUE TITLE
ObinsKit run into an error when right click into a copied layout (using pt-BR laguage)

### ISSUE THREAD

**Issue by sarmentof** [obinslab/obinslab-starter-translations#55]
Hello friends,
When i've tried to create a new layout using the copy option i run into this error.

I've copied from QWERTY library

TypeError: Error processing argument at index 2, conversion failure from 1
    at Object.normal (D:\Programas\ObinsKit\resources\electron.asar\browser\api\menu.js:225:24)
    at Menu.insertItemByType (D:\Programas\ObinsKit\resources\electron.asar\browser\api\menu.js:252:19)
    at Menu.insert (D:\Programas\ObinsKit\resources\electron.asar\browser\api\menu.js:113:20)
    at Menu.append (D:\Programas\ObinsKit\resources\electron.asar\browser\api\menu.js:104:15)
    at t.forEach (app.asar\out\main.js:6:508021)
    at Array.forEach (<anonymous>)
    at Object.n.buildContextMenu (app.asar\out\main.js:6:508006)
    at EventEmitter.s.ipcMain.on (app.asar\out\main.js:4:54594)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (D:\Programas\ObinsKit\resources\electron.asar\browser\api\web-contents.js:285:13)

Version: 1.1.4
OS: Windows 10.0.19042

**Comment by sarmentof** [comment]
Adding information, this error only occurs when I am using the Brazilian Portuguese translation.
When I am using the English language the problem does not occur.

**Comment by sarmentof** [comment]
The problem was solved after update to v1.1.5
